'$schema' = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 100 # default 30

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 1000 # default 500


## Prompt


format = """
[╭](fg:cap-separator)$os\
$directory\
$package\
$nodejs\
$python\
$git_branch\
$git_commit\
$git_status\
$fill\
$status\
$cmd_duration\
$jobs\
$container\
$shlvl\
$username\
$hostname\
$battery\
$line_break\
[╰─](fg:cap-separator)$character"""


## Color theme


palette = 'capsule'

[palettes.capsule]
black = '#000000'
bright-black = '#606060'
red = '#F95D5B'
orange = '208'
green = '#62F592'
blue = '#5DC8FD'
yellow = '#F1FA8C'
purple = '#DB61AA'
magenta = '#DB61AA'
cyan = '#94DEEE'
white = '#F1F1F0'

cap-icon       = '#202020'
cap-separator  = '#383838'
cap-background = '#383838'

cap-os         = '#F95D5B'
cap-directory  = '#aa4ded'
cap-branch     = '#62F592'
cap-duration   = '#e28c31'
cap-hostname   = '#4dede5'
cap-language   = '#4dabe9'
cap-package    = '208'
cap-nodejs     = '#c2ef58'
cap-jobs       = '#4dcfe9'
cap-status     = '#F95D5B'


## Modules - Left


[os]
format = '[─](fg:cap-separator)[](fg:cap-os)[$symbol ](fg:cap-icon bg:cap-os)[](fg:cap-os)'
disabled = false

[os.symbols]
Alpine = ''
Arch = ''
CachyOS = ''
CentOS = ''
Debian = ''
Fedora = ''
Gentoo = ''
Android = ''
Ios = '󰀷'
Linux = ''
Macos = ''
FreeBSD = ''
NetBSD = ''
OpenBSD = '󰈺'
NixOS = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
openSUSE = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = '󰍲'


[directory]
format = "[─](fg:cap-separator)[](fg:cap-directory)[ ](fg:cap-icon bg:cap-directory)[](fg:cap-directory bg:cap-background)[ $path[$read_only]($read_only_style)](bg:cap-background)[](fg:cap-background)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = ''
use_os_path_sep = false # always use /
read_only = ' 󰌾 '
read_only_style = 'fg:red bg:cap-background'


[package]
format = '[─](fg:cap-separator)[](fg:cap-package)[󰏗 ](fg:cap-icon bg:cap-package)[](fg:cap-package bg:cap-background)[ $version](bg:cap-background)[](fg:cap-background)'


[nodejs]
format = '[─](fg:cap-separator)[](fg:cap-nodejs)[󰎙 ](fg:cap-icon bg:cap-nodejs)[](fg:cap-nodejs bg:cap-background)[ $version](bg:cap-background)[](fg:cap-background)'
disabled = false


[python]
format = '[─](fg:cap-separator)[](fg:cap-language)[ ](fg:cap-icon bg:cap-language)[](fg:cap-language bg:cap-background)[ ${pyenv_prefix}(${version} )(\($virtualenv\))](bg:cap-background)[](fg:cap-background)'
version_format = 'v${major}.${minor}'


[git_branch]
format = '[─](fg:cap-separator)[](fg:cap-branch)[$symbol](fg:cap-icon bg:cap-branch)[](fg:cap-branch bg:cap-background)[ $branch(:$remote_branch)](bg:cap-background)'

[git_commit]
format = '[$tag](fg:dimmed bg:cap-background)'
tag_symbol = '  '
tag_disabled = false

[git_status]
format = '[(*$conflicted$untracked$modified$staged$renamed$deleted)](fg:red bold bg:cap-background)[](fg:cap-background)'
conflicted = '​'
untracked = '​'
modified = '​'
staged = '​'
renamed = '​'
deleted = '​'
stashed = '≡'


## Modules - Center


[fill]
symbol = '─'
style = 'fg:cap-separator'


## Modules - Right


[status]
format = '[─](fg:cap-separator)[](fg:cap-status)[ ](fg:cap-icon bg:cap-status)[](fg:cap-status bg:cap-background)[ $status](fg:red bg:cap-background)[](fg:cap-background)'
disabled = false


[cmd_duration]
min_time = 2000
format = '[─](fg:cap-separator)[](fg:cap-duration)[󱎫 ](fg:cap-icon bg:cap-duration)[](fg:cap-duration bg:cap-background)[ $duration](bg:cap-background)[](fg:cap-background)'


[jobs]
format = '[─](fg:cap-separator)[](fg:cap-jobs)[&](fg:cap-icon bg:cap-jobs)[](fg:cap-jobs bg:cap-background)[ $number](bg:cap-background)[](fg:cap-background)'
number_threshold = 1


[container]
format = '[─](fg:cap-hostname)[](fg:cap-hostname)[ ](fg:cap-icon bg:cap-hostname)[](fg:cap-hostname bg:cap-background)[ $name](bg:cap-background)[](fg:cap-background)'


[shlvl]
disabled = false
format = '[─](fg:cap-separator)[](fg:cap-background)[$symbol](bg:cap-background)[](fg:cap-background)'
repeat = true
symbol = ' '
repeat_offset = 1


[username]
format ='[─](fg:cap-separator)[](fg:$style)[ ](fg:cap-icon bg:$style)[](fg:$style bg:cap-background)[ $user](bg:cap-background)[](fg:cap-background)'
style_user = 'yellow bold'
style_root = 'red bold'
show_always = true


[hostname]
ssh_only = true
format ='[─](fg:cap-separator)[](fg:cap-hostname)[󰢹 ](fg:cap-icon bg:cap-hostname)[](fg:cap-hostname bg:cap-background)[ $hostname](bg:cap-background)[](fg:cap-background)'


[battery]
full_symbol = '󰁹'
empty_symbol = '󰂎'
format = '[─](fg:cap-separator)[](fg:$style)[$symbol ](fg:cap-icon bg:$style)[](fg:$style bg:cap-background)[ $percentage](bg:cap-background)[](fg:cap-background)'

[[battery.display]]
threshold = 80
style = 'green'
discharging_symbol = '󱊣'
charging_symbol = '󱊦'

[[battery.display]]
threshold = 50
style = 'green'
discharging_symbol = '󱊢'
charging_symbol = '󱊥'

[[battery.display]]
threshold = 30
style = 'green'
discharging_symbol = '󱊡'
charging_symbol = '󱊤'

[[battery.display]]
threshold = 15
style = 'yellow'
discharging_symbol = '󱊡'
charging_symbol = '󱊤'

[[battery.display]]
threshold = 5
style = 'red'
discharging_symbol = '󰂎'
charging_symbol = '󰢟'


## Modules - New Line


[character]
format = '$symbol '
error_symbol = '[❯](bold green)' # disable red symbol on error
