[formatting]
line_length = 80

[ai.custom_providers]

[ai.models]
custom_models = []
displayed_models = []

[diagnostics]
sql_linter = true

[mcp]
presets = []

[mcp.mcpServers]

[runtime]
auto_instantiate = false
output_max_bytes = 8000000
watcher_on_save = "lazy"
auto_reload = "off"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
default_sql_output = "auto"
default_csv_encoding = "utf-8"
reactive_tests = true

[completion]
activate_on_typing = true
signature_hint_on_typing = true
copilot = false

[snippets]
include_default_snippets = true
custom_paths = []

[package_management]
manager = "uv"

[language_servers.pylsp]
enable_pyflakes = false
enable_flake8 = false
enable_pydocstyle = false
enable_pylint = false
enabled = true
enable_mypy = true
enable_ruff = true

[display]
theme = "light"
default_table_page_size = 10
reference_highlighting = true
code_editor_font_size = 14
default_table_max_columns = 50
dataframes = "rich"
cell_output = "below"
default_width = "medium"
custom_css = [
    "/home/dmitry/.config/marimo/cell.css",
    "/home/dmitry/.config/marimo/font.css",
]

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]
"global.commandPalette" = "Ctrl-Shift-p"
"cell.delete" = "Shift-delete"
"cell.signatureHelp" = "Ctrl-q" # TODO: check
"global.toggleTerminal" = "Ctrl-`"

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"

[server]
follow_symlink = false
browser = "default"
